# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gammaDynamic <- function(y, a0, b0, w) {
    .Call(`_probintermittent_gammaDynamic`, y, a0, b0, w)
}

betaDynamic <- function(y, v, a0, b0, w) {
    .Call(`_probintermittent_betaDynamic`, y, v, a0, b0, w)
}

tweedieDensity <- function(x, mean, dispersion, power, log) {
    .Call(`_probintermittent_tweedieDensity`, x, mean, dispersion, power, log)
}

illDynamic <- function(y, p, a, w) {
    .Call(`_probintermittent_illDynamic`, y, p, a, w)
}

dampedSES <- function(y, mu0, alpha, phi) {
    .Call(`_probintermittent_dampedSES`, y, mu0, alpha, phi)
}

